version: "3.8"

services:

  postgresql:
    image: postgres:16-alpine
    container_name: api_postgresql
    ports:
      - "5444:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_20102024
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - web-api

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - web-api

#global volume
volumes:
  postgres-db-volume:

#global network
networks:
  web-api:
    driver: "bridge"