server:
  Host: localhost
  Port: 8080
  ReadTimeout: 5
  WriteTimeout: 5
  Mode: Development
  SSL: true
  JWTSecretKey: ApWynlzzJXSlWGmnu50jBYzSjaawrcXn

postgres:
  User: postgres
  Password: postgres
  Host: localhost
  Port: 5444
  Dbname: db_20102024

logger:
  Level: trace
  Caller: true
  Encoding: json
  Development: true

aws:
  Endpoint: http://localhost:9000