server:
  Host: localhost # Required
  Port: 8080 # Required
  ReadTimeout: 5 # Required
  WriteTimeout: 5 # Required
  Mode: Development # Required
  SSL: true # Required
  JWTSecretKey: ApWynlzzJXSlWGmnu50jBYzSjaawrcXn # Required

postgres:
  User: postgres # Required
  Password: postgres # Required
  Host: localhost # Required
  Port: 5444 # Required
  Dbname: db_20102024 # Required

redis:
  Addr: localhost:6379
  DB: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""

logger:
  Level: trace # Required [trace, debug, info, warn, error, fatal, panic]
  Caller: true # Required [true, false]
  Encoding: json # Optional [json, text], default json
  Development: true

aws:
  Endpoint: localhost:9000
  MinioEndpoint: http://127.0.0.1:9000
  MinioAccessKey: iuqiDShZCCDZGPYJxoSX
  MinioSecretKey: qSHe9dzo0GlZtikQfrzH0ARiHOXojRcRYh3Q1sSk
  UseSSL: false

#public MinIO cluster
#aws:
#  Endpoint: play.min.io
#  MinioAccessKey: Q3AM3UQ867SPQQA43P2F
#  MinioSecretKey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG